Pig Stack Trace
---------------
ERROR 1000: Error during parsing. Encountered " <IDENTIFIER> "GENERATE "" at line 2, column 1.
Was expecting one of:
    <EOF> 
    "cat" ...
    "clear" ...
    "fs" ...
    "sh" ...
    "cd" ...
    "cp" ...
    "copyFromLocal" ...
    "copyToLocal" ...
    "dump" ...
    "\\d" ...
    "describe" ...
    "\\de" ...
    "aliases" ...
    "explain" ...
    "\\e" ...
    "help" ...
    "history" ...
    "kill" ...
    "ls" ...
    "mv" ...
    "mkdir" ...
    "pwd" ...
    "quit" ...
    "\\q" ...
    "register" ...
    "rm" ...
    "rmf" ...
    "set" ...
    "illustrate" ...
    "\\i" ...
    "run" ...
    "exec" ...
    "scriptDone" ...
    "" ...
    "" ...
    <EOL> ...
    ";" ...
    

org.apache.pig.tools.pigscript.parser.ParseException: Encountered " <IDENTIFIER> "GENERATE "" at line 2, column 1.
Was expecting one of:
    <EOF> 
    "cat" ...
    "clear" ...
    "fs" ...
    "sh" ...
    "cd" ...
    "cp" ...
    "copyFromLocal" ...
    "copyToLocal" ...
    "dump" ...
    "\\d" ...
    "describe" ...
    "\\de" ...
    "aliases" ...
    "explain" ...
    "\\e" ...
    "help" ...
    "history" ...
    "kill" ...
    "ls" ...
    "mv" ...
    "mkdir" ...
    "pwd" ...
    "quit" ...
    "\\q" ...
    "register" ...
    "rm" ...
    "rmf" ...
    "set" ...
    "illustrate" ...
    "\\i" ...
    "run" ...
    "exec" ...
    "scriptDone" ...
    "" ...
    "" ...
    <EOL> ...
    ";" ...
    
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.generateParseException(PigScriptParser.java:1428)
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.handle_invalid_command(PigScriptParser.java:1236)
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:710)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:228)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:203)
	at org.apache.pig.tools.grunt.Grunt.run(Grunt.java:66)
	at org.apache.pig.Main.run(Main.java:542)
	at org.apache.pig.Main.main(Main.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
================================================================================
Pig Stack Trace
---------------
ERROR 1000: Error during parsing. Encountered " <PATH> "udf.test "" at line 2, column 10.
Was expecting one of:
    <EOF> 
    "cat" ...
    "clear" ...
    "fs" ...
    "sh" ...
    "cd" ...
    "cp" ...
    "copyFromLocal" ...
    "copyToLocal" ...
    "dump" ...
    "\\d" ...
    "describe" ...
    "\\de" ...
    "aliases" ...
    "explain" ...
    "\\e" ...
    "help" ...
    "history" ...
    "kill" ...
    "ls" ...
    "mv" ...
    "mkdir" ...
    "pwd" ...
    "quit" ...
    "\\q" ...
    "register" ...
    "rm" ...
    "rmf" ...
    "set" ...
    "illustrate" ...
    "\\i" ...
    "run" ...
    "exec" ...
    "scriptDone" ...
    "" ...
    "" ...
    <EOL> ...
    ";" ...
    

org.apache.pig.tools.pigscript.parser.ParseException: Encountered " <PATH> "udf.test "" at line 2, column 10.
Was expecting one of:
    <EOF> 
    "cat" ...
    "clear" ...
    "fs" ...
    "sh" ...
    "cd" ...
    "cp" ...
    "copyFromLocal" ...
    "copyToLocal" ...
    "dump" ...
    "\\d" ...
    "describe" ...
    "\\de" ...
    "aliases" ...
    "explain" ...
    "\\e" ...
    "help" ...
    "history" ...
    "kill" ...
    "ls" ...
    "mv" ...
    "mkdir" ...
    "pwd" ...
    "quit" ...
    "\\q" ...
    "register" ...
    "rm" ...
    "rmf" ...
    "set" ...
    "illustrate" ...
    "\\i" ...
    "run" ...
    "exec" ...
    "scriptDone" ...
    "" ...
    "" ...
    <EOL> ...
    ";" ...
    
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.generateParseException(PigScriptParser.java:1428)
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.handle_invalid_command(PigScriptParser.java:1236)
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:710)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:228)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:203)
	at org.apache.pig.tools.grunt.Grunt.run(Grunt.java:66)
	at org.apache.pig.Main.run(Main.java:542)
	at org.apache.pig.Main.main(Main.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
================================================================================
Pig Stack Trace
---------------
ERROR 1200: Pig script failed to parse: 
<line 1, column 18> Undefined alias: fares

Failed to parse: Pig script failed to parse: 
<line 1, column 18> Undefined alias: fares
	at org.apache.pig.parser.QueryParserDriver.parse(QueryParserDriver.java:196)
	at org.apache.pig.PigServer$Graph.validateQuery(PigServer.java:1684)
	at org.apache.pig.PigServer$Graph.registerQuery(PigServer.java:1657)
	at org.apache.pig.PigServer.registerQuery(PigServer.java:600)
	at org.apache.pig.tools.grunt.GruntParser.processPig(GruntParser.java:1069)
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:501)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:228)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:203)
	at org.apache.pig.tools.grunt.Grunt.run(Grunt.java:66)
	at org.apache.pig.Main.run(Main.java:542)
	at org.apache.pig.Main.main(Main.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
Caused by: 
<line 1, column 18> Undefined alias: fares
	at org.apache.pig.parser.AstValidator.validateAliasRef(AstValidator.java:278)
	at org.apache.pig.parser.AstValidator.rel(AstValidator.java:6526)
	at org.apache.pig.parser.AstValidator.foreach_clause(AstValidator.java:13915)
	at org.apache.pig.parser.AstValidator.op_clause(AstValidator.java:1923)
	at org.apache.pig.parser.AstValidator.general_statement(AstValidator.java:1035)
	at org.apache.pig.parser.AstValidator.statement(AstValidator.java:499)
	at org.apache.pig.parser.AstValidator.query(AstValidator.java:373)
	at org.apache.pig.parser.QueryParserDriver.validateAst(QueryParserDriver.java:255)
	at org.apache.pig.parser.QueryParserDriver.parse(QueryParserDriver.java:183)
	... 15 more
================================================================================
Pig Stack Trace
---------------
ERROR 1003: Unable to find an operator for alias puttest

org.apache.pig.impl.logicalLayer.FrontendException: ERROR 1003: Unable to find an operator for alias puttest
	at org.apache.pig.PigServer$Graph.buildPlan(PigServer.java:1521)
	at org.apache.pig.PigServer.storeEx(PigServer.java:1006)
	at org.apache.pig.PigServer.store(PigServer.java:974)
	at org.apache.pig.PigServer.openIterator(PigServer.java:887)
	at org.apache.pig.tools.grunt.GruntParser.processDump(GruntParser.java:752)
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:372)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:228)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:203)
	at org.apache.pig.tools.grunt.Grunt.run(Grunt.java:66)
	at org.apache.pig.Main.run(Main.java:542)
	at org.apache.pig.Main.main(Main.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
================================================================================
Pig Stack Trace
---------------
ERROR 1002: Unable to store alias outtest

org.apache.pig.impl.logicalLayer.FrontendException: ERROR 1066: Unable to open iterator for alias outtest
	at org.apache.pig.PigServer.openIterator(PigServer.java:912)
	at org.apache.pig.tools.grunt.GruntParser.processDump(GruntParser.java:752)
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:372)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:228)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:203)
	at org.apache.pig.tools.grunt.Grunt.run(Grunt.java:66)
	at org.apache.pig.Main.run(Main.java:542)
	at org.apache.pig.Main.main(Main.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
Caused by: org.apache.pig.PigException: ERROR 1002: Unable to store alias outtest
	at org.apache.pig.PigServer.storeEx(PigServer.java:1015)
	at org.apache.pig.PigServer.store(PigServer.java:974)
	at org.apache.pig.PigServer.openIterator(PigServer.java:887)
	... 12 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: outtest: Store(hdfs://cluster.cusp.nyu.edu:9000/tmp/temp-1165669609/tmp-257665208:org.apache.pig.impl.io.InterStorage) - scope-3 Operator Key: scope-3): org.apache.pig.impl.streaming.StreamingUDFException: LINE : Traceback (most recent call last):
  File "/tmp/controller189315021123871983.py", line 338, in <module>
    sys.argv[5], sys.argv[6], sys.argv[7], sys.argv[8])
  File "/tmp/controller189315021123871983.py", line 77, in main
    self.output_stream = open(output_stream_path, 'a')
IOError: [Errno 2] No such file or directory: '/localhome/hdfs/logs/udfOutput/test.out'

	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:289)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POStore.getNextTuple(POStore.java:143)
	at org.apache.pig.backend.hadoop.executionengine.fetch.FetchLauncher.runPipeline(FetchLauncher.java:160)
	at org.apache.pig.backend.hadoop.executionengine.fetch.FetchLauncher.launchPig(FetchLauncher.java:81)
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.launchPig(HExecutionEngine.java:275)
	at org.apache.pig.PigServer.launchPlan(PigServer.java:1367)
	at org.apache.pig.PigServer.executeCompiledLogicalPlan(PigServer.java:1352)
	at org.apache.pig.PigServer.storeEx(PigServer.java:1011)
	... 14 more
Caused by: org.apache.pig.impl.streaming.StreamingUDFException: LINE : Traceback (most recent call last):
  File "/tmp/controller189315021123871983.py", line 338, in <module>
    sys.argv[5], sys.argv[6], sys.argv[7], sys.argv[8])
  File "/tmp/controller189315021123871983.py", line 77, in main
    self.output_stream = open(output_stream_path, 'a')
IOError: [Errno 2] No such file or directory: '/localhome/hdfs/logs/udfOutput/test.out'

	at org.apache.pig.impl.builtin.StreamingUDF$ProcessErrorThread.run(StreamingUDF.java:459)
================================================================================
